@startuml
'https://plantuml.com/sequence-diagram

class App {
    - path : String
    - outputFile : String

    + getUserInput()
}

class FileUtilities {

    + createFile()
    + readFromFile()
    + writeToFile()
}

App <|-- FileUtilities
@enduml